services:
    mysql_dev:
        image: mariadb:11
        environment:
            - MARIADB_ROOT_PASSWORD=1234
            - MARIADB_DATABASE=whatsapp
            - MARIADB_USER=admin
            - MARIADB_PASSWORD=1234
        expose:
            - '3306'
        ports:
            - '3306:3306'
        restart: always
        container_name: whatsapp_db
        volumes:
            - whatsapp:/var/lib/mysql

volumes:
    whatsapp:
